services:
  reservei-db:
    image: "postgres:18.1-alpine3.23"
    container_name: "reservei_postgres"
    environment:
      POSTGRES_USER: local_user
      POSTGRES_DB: local_db
      POSTGRES_PASSWORD: local_password
    ports:
      - "5432:5432"
